routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/user','UserController');

Route::resource('/document','DocumentController');

Route::resource('/student','studentController');
<<<<<<< HEAD

Route::resource("/document2","DocumentController2");
=======
>>>>>>> 9f88a3fbc580bda6b9fa0de351308f129b5e6fec

app/Document.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Document extends Model
{
    protected $fillable =['name','description'];
}

app/Http/Controllers/DocumentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Document;
<<<<<<< HEAD
use Validator;

class DocumentController extends Controller
{
    public function __Construct(){        
        $this->middleware('auth');             
    }
    
=======

class DocumentController extends Controller
{
>>>>>>> 9f88a3fbc580bda6b9fa0de351308f129b5e6fec
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
<<<<<<< HEAD
        $this->authorize('isAdmin');           
=======
>>>>>>> 9f88a3fbc580bda6b9fa0de351308f129b5e6fec
        $documents = Document::all();
        return view('Document.index',compact('documents'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Document.new');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
<<<<<<< HEAD
    public function store(Request $request)    
    {
        $validacion = Validator::make($request->all(), [
            'name' => 'required|alpha_num|max:100',
            'description' => 'required']);

        if($validacion->fails()) {    
            return response()->json($validacion->messages(), 422);
        } else {
            $document = Document::create($request->all());        
            return response()->json(['respuesta' => 'correcto']);
         }
=======
    public function store(Request $request)
    {
        $document = Document::create($request->all());        
        return response()->json(['respuesta' => 'correcto']);
>>>>>>> 9f88a3fbc580bda6b9fa0de351308f129b5e6fec
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $document = Document::findOrFail($id);
        return view('Document.edit',compact('document'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $document = Document::findOrFail($id);
        $document->fill($request->all());
        $document->save();
        return response()->json(['respuesta' => 'correcto']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
<<<<<<< HEAD

=======
>>>>>>> 9f88a3fbc580bda6b9fa0de351308f129b5e6fec
        $document = Document::findOrfail($id);
        $document->delete();
        return response()->json(['respuesta' => 'correcto']);
    }
}

app/Http/Controllers/api/DocumentController.php
<?php

namespace App\Http\Controllers\api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Document;
Use DataTables;

class DocumentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $documents = Document::all();
        return Datatables::of($documents)->make(true);

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/Document/edit.blade.php
@extends('layouts.master')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-10">
        <div class="card card-primary mt-3">
            <div class="card-header">
                <h3 class="card-title">Editar Documento</h3>                    
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form id = "frm-editar" class="form-horizontal" method="post" action="">
                @csrf
                <input type="hidden" id="id" name="id" value="{{$document->id}}">
                <div class="card-body">
                    <div class="form-group">
                        <label for="name" class="col-sm-2 control-label font-weight-bold">Nombre</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="name" 
                                placeholder="Name" name="name" value="{{$document->name}}">
                        </div>
                    </div>
                   
                    <div class="form-group">
                        <label for="description" class="col-sm-2 control-label font-weight-bold">Descripción</label>
                        <div class="col-sm-10">
                        <textarea cols="50" rows="3" class="form-control" id="description" placeholder="Descripción" 
                            name="description">{{$document->description}}</textarea>
                        </div>
                    </div>
                    
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                <button id="bnt-actualizar" title="Graba el nuevo documento" class="btn btn-primary">Guardar</button>
                <a href="/document" title="Retorna al listado de documentos" class="btn btn-danger float-right">Cancelar</a>
                </div>
                <!-- /.card-footer -->
            </form>
        </div>
        </div>
    </div>
</div>
@endsection

@section('script')
    <script src="/js/documents.js"></script>
@endsection

resources/views/Document/index.blade.php
@extends('layouts.master')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Lista de Documentos</h3>
                    <div class="card-tools">
                        <a href="{{route('document.create')}}" title="Registrar un nuevo Documento" class="btn btn-success">Registrar<i class="fas fa-plus-circle fa-lg ml-3"></i></a>
                    </div>                    
                </div>
                @include("commons.success")
                <div class="card-body">
                   <table id="tabla" class="table table-striped">
                   <thead>
                    <tr>
                        <th>id</th>
                        <th>Nombre</th>
                        <th>Descripción</th>
                        <th>Modificar</th>
                    </tr>
                    </thead>
                    <tbody>

                    </tbody>
                   </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('script')
<script src="/js/documents.js"></script>
@endsection

resources/views/Document/index2.blade.php
@extends('layouts.master')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Lista de Documentos</h3>
                    <div class="card-tools">
                        <a href="{{route('document2.create')}}" title="Registrar un nuevo Documento" class="btn btn-success">Registrar<i class="fas fa-plus-circle fa-lg ml-3"></i></a>
                    </div>                    
                </div>
                @include("commons.success")
                <div class="card-body">
                   <table id="tabla" class="table table-striped">
                   <thead>
                    <tr>
                        <th>id</th>
                        <th>Nombre</th>
                        <th>Descripción</th>
                        <th>Modificar</th>
                    </tr>
                    </thead>
                    <tbody>

                    </tbody>
                   </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('script')
<script src="/js/documents.js"></script>
@endsection

resources/views/Document/new.blade.php
@extends('layouts.master')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-10">
        <div class="card card-primary mt-3">
            <div class="card-header">
                <h3 class="card-title">Nuevo Documento</h3>                    
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form id = "frm-grabar" class="form-horizontal" method="post" action="">
                @csrf
                <div class="card-body">
                    <div class="form-group">
                        <label for="name" class="col-sm-2 control-label font-weight-bold">Nombre</label>
                        <div class="col-sm-10">
<<<<<<< HEAD
                            <input type="text" class="form-control" id="name" 
                                placeholder="Name" name="name"
                                data-validation="alphanumeric"
                                data-validation="required" > 
                                <span class="text-danger name-error mt-5" hidden></span>    
                                                  
=======
                            <input type="text" class="form-control" id="name" placeholder="Name" name="name">
>>>>>>> 9f88a3fbc580bda6b9fa0de351308f129b5e6fec
                        </div>
                    </div>
                   
                    <div class="form-group">
                        <label for="description" class="col-sm-2 control-label font-weight-bold">Descripción</label>
                        <div class="col-sm-10">
<<<<<<< HEAD
                            <textarea cols="50" rows="3" class="form-control" id="description" placeholder="Descripción" 
                                name="description"
                                data-validation="required" ></textarea>
                                <span class="text-danger description-error mt-5" hidden></span>
=======
                        <textarea cols="50" rows="3" class="form-control" id="description" placeholder="Descripción" 
                            name="description"></textarea>
>>>>>>> 9f88a3fbc580bda6b9fa0de351308f129b5e6fec
                        </div>
                    </div>
                    
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                <button id="bnt-grabar" title="Graba el nuevo documento" class="btn btn-primary">Guardar</button>
                <a href="/document" title="Retorna al listado de documentos" class="btn btn-danger float-right">Cancelar</a>
                </div>
                <!-- /.card-footer -->
            </form>
        </div>
        </div>
    </div>
</div>
@endsection

@section('script')
    <script src="/js/documents.js"></script>
@endsection

resources/views/Document/new2.blade.php
@extends('layouts.master')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-10">
        <div class="card card-primary mt-3">
            <div class="card-header">
                <h3 class="card-title">Nuevo Documento</h3>                    
            </div>

            
            <!-- /.card-header -->
            <!-- form start -->
            <form id = "frm-grabar" class="form-horizontal" method="post" action="{{route('document.show')}">
                @csrf
                <div class="card-body">
                    <div class="form-group">
                        <label for="name" class="col-sm-2 control-label font-weight-bold">Nombre</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control" id="name" 
                                placeholder="Name" name="name">
                        </div>
                    </div>
                   
                    <div class="form-group">
                        <label for="description" class="col-sm-2 control-label font-weight-bold">Descripción</label>
                        <div class="col-sm-10">
                        <textarea cols="50" rows="3" class="form-control" id="description" placeholder="Descripción" 
                            name="description"
                            ></textarea>
                        </div>
                    </div>
                    
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                <input id="bnt-grabar2" type="submit" title="Graba el nuevo documento" class="btn btn-primary" value="Guardar">
                <a href="/document" title="Retorna al listado de documentos" class="btn btn-danger float-right">Cancelar</a>
                </div>
                <!-- /.card-footer -->
            </form>
        </div>
        </div>
    </div>
</div>
@endsection

@section('script')
    
@endsection